### ISSUE TITLE
kcbench uses two threads per logical core

### ISSUE THREAD

**Issue by aa-ko** [knurd/kcbench#5]
Hi :)
kcbench seems to create four threads for each physical core, because `nproc --all` already reports the number of logical cores (including Hyperthreading). Is this intended?

https://github.com/knurd/kcbench/blob/2f1c749ec10b02557dd084761bc576647d10c079/kcbench#L41

**Comment by knurd** [comment]
Is this intended? Well, yes and no :-/

kcbench started when ordinary PCs still used single core CPUs; some with SMT, some without. Back then we did some measurements where a single core machine with SMT performed best when compiling Linux with "make -j 4". When Dual Core became standard it didn't matter that much any more, but still it often was quicker with "number of CPUs * 2 ". We assumed that that's because there immediately is something for a core or a sibling to do (e.g. without any further I/O), as soon as another cc process finished.

But well, with machines that have 8 or even more cores I guess "number of CPUs * 2 " doesn't make much sense anymore. But I guess "nproc --all" OTOHO might not be the best choice either. Guess I need to find a middle ground here. For a 8 core cpu mit smt something like 24 or 28 might be appropriate. Or what would you suggest? I'll try to test a bit next week, maybe that will help be decide.

**Comment by knurd** [comment]
FWIW, I did a few tests and on most systems i tried it didn't matter much if I used (nproc --all) or ((nproc --all)*2) – some where a little bit quicker with the former, some with the latter. I was thus inclined to change the default to (nproc --all) and even committed that already. But I will revert it, as today I found a setting where it the difference was bigger: with (nproc --all) kcbench compiled an allmodconfig (a new test option I'll commit soonish) in 331 seconds, with ((nproc --all)*2) in just 316 – and thus 15 seconds less!

**Comment by knurd** [comment]
Better late than never: I did a few tests and reworked the default. What kcbench doesn now is described in the updated man page. See here for details:

https://github.com/knurd/kcbench/commit/9102154e4330c0ce570c237636d61967d4760889#diff-3464925ae3c7b233e0759a3c17571588R140

**Comment by aa-ko** [comment]
@knurd I'm sorry, for some reason I totally missed your updates on this. The update is amazing and much more sophisticated than I had hoped for. Thank you so much for this awesome benchmarking tool!

**Comment by knurd** [comment]
> Thank you so much for this awesome benchmarking tool!

Glad you like it, was quite a bit of work, but I think it was worth it. I got one or two similar comments, but apart from that not much more feedback and nothing concrete.

What I really would like to see: some feedback from new or existing users that show the pitfalls or point out things that the man page doesn't explain properly (IOW: problems I as the developer don't notice…). So if you spot anything where improvements are needed or would be wise just let me know, would be much appreciated!
